### Criando uma Base

In [2]:
import pandas as pd

dados = {
    'Nome': ['Ana', 'Pedro', 'Júlio', 'Carlos', 'Maria'],
    'Idade': [25, 30, 22, 40, 35],
    'Salário':[3000,5000,4000,7000,6000]
}

df = pd.DataFrame(dados)
df

     Nome  Idade  Salário
0     Ana     25     3000
1   Pedro     30     5000
2   Júlio     22     4000
3  Carlos     40     7000
4   Maria     35     6000

### Primeira Inspeção

In [3]:
df.head()

     Nome  Idade  Salário
0     Ana     25     3000
1   Pedro     30     5000
2   Júlio     22     4000
3  Carlos     40     7000
4   Maria     35     6000

In [5]:
df.shape

(5, 3)

In [6]:
df.columns

Index(['Nome', 'Idade', 'Salário'], dtype='object')

In [9]:
df.dtypes

Nome       object
Idade       int64
Salário     int64
dtype: object