### Criando uma Base

In [92]:
import pandas as pd

dados = {
    'Nome': ['Ana', 'Pedro', 'Júlio', 'Carlos', 'Maria'],
    'Idade': [25, 30, 22, 40, 35],
    'Salário':[3000,5000,4000,7000,6000]
}

df = pd.DataFrame(dados)
df

     Nome  Idade  Salário
0     Ana     25     3000
1   Pedro     30     5000
2   Júlio     22     4000
3  Carlos     40     7000
4   Maria     35     6000

### Primeira Inspeção

In [95]:
df.head()

     Nome  Idade  Salário
0     Ana     25     3000
1   Pedro     30     5000
2   Júlio     22     4000
3  Carlos     40     7000
4   Maria     35     6000

In [97]:
df.shape

(5, 3)

In [98]:
df.columns

Index(['Nome', 'Idade', 'Salário'], dtype='object')

In [101]:
df.dtypes

Nome       object
Idade       int64
Salário     int64
dtype: object

In [102]:
df.describe()

           Idade     Salário
count   5.000000     5.00000
mean   30.400000  5000.00000
std     7.300685  1581.13883
min    22.000000  3000.00000
25%    25.000000  4000.00000
50%    30.000000  5000.00000
75%    35.000000  6000.00000
max    40.000000  7000.00000

### Média

In [104]:
df.Salário.mean()

np.float64(5000.0)

### Maior salário:

In [106]:
df.Salário.mean()

np.float64(5000.0)

### Menor salário:

In [107]:
df.Salário.min()

3000

### Mediana

In [108]:
df.Salário.median()

5000.0

# Parte 5 — Filtrando Dados

Salário acima de 5000:

In [109]:
df[df['Salário'] > 5000]

     Nome  Idade  Salário
3  Carlos     40     7000
4   Maria     35     6000

Idade menor que 30:

In [110]:
df[df['Idade'] < 30]

    Nome  Idade  Salário
0    Ana     25     3000
2  Júlio     22     4000

Duas condições maior que 25 e maior que 4000:

In [112]:
df[
    (df['Salário'] > 4000) & (df['Idade'] > 25)
]

     Nome  Idade  Salário
1   Pedro     30     5000
3  Carlos     40     7000
4   Maria     35     6000

Duas condições maior que 30 ou primeira letra do nome M:

In [113]:
df[
    (df['Nome'] > 'A*') | (df['Idade'] > 30)
]

     Nome  Idade  Salário
0     Ana     25     3000
1   Pedro     30     5000
2   Júlio     22     4000
3  Carlos     40     7000
4   Maria     35     6000

## Exercício 3

1. Pessoas com salário acima de 4000.

In [114]:
df[df['Salário'] > 4000]

     Nome  Idade  Salário
1   Pedro     30     5000
3  Carlos     40     7000
4   Maria     35     6000

2. Pessoas com idade maior que 30.

In [115]:
df[df['Idade'] > 30]

     Nome  Idade  Salário
3  Carlos     40     7000
4   Maria     35     6000

3. Pessoas com idade acima de 25 e salário acima de 5000.

In [116]:
df[
    (df['Salário'] > 5000) & (df['Idade'] > 25)
]

     Nome  Idade  Salário
3  Carlos     40     7000
4   Maria     35     6000

# Parte 6 — Criando Novas Colunas

Salário anual:

In [118]:
df['Salário_anual'] = df['Salário'] * 12
df

     Nome  Idade  Salário  Salário_anual
0     Ana     25     3000          36000
1   Pedro     30     5000          60000
2   Júlio     22     4000          48000
3  Carlos     40     7000          84000
4   Maria     35     6000          72000

## Exercício 4

### Adicionar o bônus salarial de 10%

In [119]:
df['Bonus_Salario'] = df['Salário'] * 0.1
df

     Nome  Idade  Salário  Salário_anual  Bonus_Salario
0     Ana     25     3000          36000          300.0
1   Pedro     30     5000          60000          500.0
2   Júlio     22     4000          48000          400.0
3  Carlos     40     7000          84000          700.0
4   Maria     35     6000          72000          600.0

# Mini Projeto do Dia

### Você é analista de RH.
Descobrir:

- média salarial

In [120]:
df.Salário.mean()

np.float64(5000.0)

In [121]:
df.Salário

0    3000
1    5000
2    4000
3    7000
4    6000
Name: Salário, dtype: int64

- maior salário

In [122]:
df.Salário.max()

7000

- menor salário

3000

- funcionários acima da média

      Nome  Idade  Salário  Salario_Anual  Bonus_Salario
3  Mariane     40     7000          84000          700.0
4   Creuza     35     6000          72000          600.0

# Desafio Profissional

Adicione mais 5 funcionários ao DataFrame.

0    Joaquim
1      Alyne
2       João
3    Mariane
4     Creuza
Name: Nome, dtype: object