In [1]:
import pandas as pd

In [2]:
data = {
    'calories': [420,380,390],
    'duration':[50,40,45]
}

### Load data into a DataFrame object:

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   calories  duration
0       420        50
1       380        40
2       390        45

In [6]:
df.loc[0]

calories    420
duration     50
Name: 0, dtype: int64

In [7]:
df.loc[[0,1]]

   calories  duration
0       420        50
1       380        40

In [8]:
df = pd.DataFrame(data, index = ['day1', 'day2', 'day3'])

In [9]:
df

      calories  duration
day1       420        50
day2       380        40
day3       390        45