In [1]:
import pandas as pd

In [2]:
dados ={
    'nome':['Joao', 'Maria', 'joao', 'Pedro', 'Ana'],
    'idade':[32, None, 32, 150,28],
    'cidade':['Anápolis', 'Goiânia', 'Anápolis', 'Brasília', 'GOIÂNIA'],
    'salario':[4500,5200,4500,-100,None]

}

In [3]:
df = pd.DataFrame(dados)

In [4]:
df

    nome  idade    cidade  salario
0   Joao   32.0  Anápolis   4500.0
1  Maria    NaN   Goiânia   5200.0
2   joao   32.0  Anápolis   4500.0
3  Pedro  150.0  Brasília   -100.0
4    Ana   28.0   GOIÂNIA      NaN

In [5]:
df.isna()

    nome  idade  cidade  salario
0  False  False   False    False
1  False   True   False    False
2  False  False   False    False
3  False  False   False    False
4  False  False   False     True

In [6]:
df.isna().sum()

nome       0
idade      1
cidade     0
salario    1
dtype: int64

In [7]:
df.isnull()

    nome  idade  cidade  salario
0  False  False   False    False
1  False   True   False    False
2  False  False   False    False
3  False  False   False    False
4  False  False   False     True

In [8]:
percentual = df.isna().mean() * 100
percentual

nome        0.0
idade      20.0
cidade      0.0
salario    20.0
dtype: float64

In [9]:
df['idade'].fillna(30)

0     32.0
1     30.0
2     32.0
3    150.0
4     28.0
Name: idade, dtype: float64

In [10]:
media = df['idade'].mean()

In [11]:
df['idade'] = df['idade'].fillna(media)
df

    nome  idade    cidade  salario
0   Joao   32.0  Anápolis   4500.0
1  Maria   60.5   Goiânia   5200.0
2   joao   32.0  Anápolis   4500.0
3  Pedro  150.0  Brasília   -100.0
4    Ana   28.0   GOIÂNIA      NaN

In [12]:
df['idade'].describe()

count      5.000000
mean      60.500000
std       51.698646
min       28.000000
25%       32.000000
50%       32.000000
75%       60.500000
max      150.000000
Name: idade, dtype: float64

In [13]:
df['idade_valida'] = ((df['idade'] >=0) & (df['idade'] <= 120))
df

    nome  idade    cidade  salario  idade_valida
0   Joao   32.0  Anápolis   4500.0          True
1  Maria   60.5   Goiânia   5200.0          True
2   joao   32.0  Anápolis   4500.0          True
3  Pedro  150.0  Brasília   -100.0         False
4    Ana   28.0   GOIÂNIA      NaN          True

In [15]:
df.loc[(df['idade'] <0) | (df['idade'] > 120), 'idade'] = None
df

    nome  idade    cidade  salario  idade_valida
0   Joao   32.0  Anápolis   4500.0          True
1  Maria   60.5   Goiânia   5200.0          True
2   joao   32.0  Anápolis   4500.0          True
3  Pedro    NaN  Brasília   -100.0         False
4    Ana   28.0   GOIÂNIA      NaN          True

In [16]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [17]:
df.duplicated().sum()

np.int64(0)

In [19]:
df = df.drop_duplicates()
df

    nome  idade    cidade  salario  idade_valida
0   Joao   32.0  Anápolis   4500.0          True
1  Maria   60.5   Goiânia   5200.0          True
2   joao   32.0  Anápolis   4500.0          True
3  Pedro    NaN  Brasília   -100.0         False
4    Ana   28.0   GOIÂNIA      NaN          True

In [21]:
df['nome'] = df['nome'].str.lower()
df

    nome  idade    cidade  salario  idade_valida
0   joao   32.0  Anápolis   4500.0          True
1  maria   60.5   Goiânia   5200.0          True
2   joao   32.0  Anápolis   4500.0          True
3  pedro    NaN  Brasília   -100.0         False
4    ana   28.0   GOIÂNIA      NaN          True

In [22]:
df['nome'] = df['nome'].str.strip()
df

    nome  idade    cidade  salario  idade_valida
0   joao   32.0  Anápolis   4500.0          True
1  maria   60.5   Goiânia   5200.0          True
2   joao   32.0  Anápolis   4500.0          True
3  pedro    NaN  Brasília   -100.0         False
4    ana   28.0   GOIÂNIA      NaN          True

In [23]:
df['nome'] = df['nome'].str.title()
df

    nome  idade    cidade  salario  idade_valida
0   Joao   32.0  Anápolis   4500.0          True
1  Maria   60.5   Goiânia   5200.0          True
2   Joao   32.0  Anápolis   4500.0          True
3  Pedro    NaN  Brasília   -100.0         False
4    Ana   28.0   GOIÂNIA      NaN          True

In [24]:
df.duplicated().sum()
df

    nome  idade    cidade  salario  idade_valida
0   Joao   32.0  Anápolis   4500.0          True
1  Maria   60.5   Goiânia   5200.0          True
2   Joao   32.0  Anápolis   4500.0          True
3  Pedro    NaN  Brasília   -100.0         False
4    Ana   28.0   GOIÂNIA      NaN          True

In [25]:
df['nome'].duplicated()

0    False
1    False
2     True
3    False
4    False
Name: nome, dtype: bool

In [26]:
df['nome'].value_counts()

nome
Joao     2
Maria    1
Pedro    1
Ana      1
Name: count, dtype: int64

In [28]:
df['cidade'] = (df['cidade'].str.strip().str.lower().str.title())
df

    nome  idade    cidade  salario  idade_valida
0   Joao   32.0  Anápolis   4500.0          True
1  Maria   60.5   Goiânia   5200.0          True
2   Joao   32.0  Anápolis   4500.0          True
3  Pedro    NaN  Brasília   -100.0         False
4    Ana   28.0   Goiânia      NaN          True

In [29]:
df['cidade'].value_counts()

cidade
Anápolis    2
Goiânia     2
Brasília    1
Name: count, dtype: int64

In [30]:
df.dtypes

nome             object
idade           float64
cidade           object
salario         float64
idade_valida       bool
dtype: object