In [1]:
import pandas as pd

In [3]:
dados = {
    'nome':['joão', 'MARIA', 'João', 'pedro', 'ANA'],
    'idade':[30,None, 30,200,25],
    'cidade':['goiania', 'Goiânia', 'GOIANIA', 'Brasília', ' brasilia '],
    'salario':[3500,4200,3500,-500,None]
}

In [4]:
df = pd.DataFrame(dados)
df

    nome  idade      cidade  salario
0   joão   30.0     goiania   3500.0
1  MARIA    NaN     Goiânia   4200.0
2   João   30.0     GOIANIA   3500.0
3  pedro  200.0    Brasília   -500.0
4    ANA   25.0   brasilia       NaN

In [5]:
df['nome'] = (df['nome'].str.lower().str.strip().str.capitalize())
df

    nome  idade      cidade  salario
0   João   30.0     goiania   3500.0
1  Maria    NaN     Goiânia   4200.0
2   João   30.0     GOIANIA   3500.0
3  Pedro  200.0    Brasília   -500.0
4    Ana   25.0   brasilia       NaN