### Código ETL

In [1]:
import pandas as pd

### Extract

In [2]:
dados = pd.read_csv('clientes.csv')
dados

   id   nome  idade          cidade
0   1    Ana     22       São Paulo
1   2  Bruno     35  Rio de Janeiro
2   3  Carla     29       São Paulo
3   4  Diego     41          Recife
4   5    Eva     30        Curitiba

### Trasform

In [4]:
dados['nome'] = dados['nome'].str.upper()
dados_sp = dados[dados['cidade'] == "São Paulo"]
dados_sp

   id   nome  idade     cidade
0   1    ANA     22  São Paulo
2   3  CARLA     29  São Paulo