### Questão 1 - Extract

Leia os dois arquivos CSV usando Pandas.

In [1]:
import pandas as pd

In [2]:
clientes = pd.read_csv('clientes.csv')
vendas = pd.read_csv('vendas.csv')

Mostrar as 5 primeiras linhas de cada DataFrame.

In [3]:
clientes.head()

   cliente_id   nome  idade          cidade
0           1    Ana     22       São Paulo
1           2  Bruno     35  Rio de Janeiro
2           3  Carla     29       São Paulo
3           4  Diego     41          Recife
4           5    Eva     30        Curitiba

In [4]:
vendas.head()

   venda_id  cliente_id   produto  valor        data
0       101           1  Notebook   3500  2025-01-10
1       102           2     Mouse     80  2025-01-11
2       103           1   Teclado    150  2025-01-12
3       104           3   Monitor   1200  2025-01-13
4       105           4  Notebook   3500  2025-01-14

### Questão 2 - Transform

Converta todos os nomes dos clientes para MAIÚSCULO.

In [5]:
clientes.head()

   cliente_id   nome  idade          cidade
0           1    Ana     22       São Paulo
1           2  Bruno     35  Rio de Janeiro
2           3  Carla     29       São Paulo
3           4  Diego     41          Recife
4           5    Eva     30        Curitiba

In [9]:
clientes['nome'] = clientes['nome'].str.upper()
clientes

   cliente_id      nome  idade          cidade
0           1       ANA     22       São Paulo
1           2     BRUNO     35  Rio de Janeiro
2           3     CARLA     29       São Paulo
3           4     DIEGO     41          Recife
4           5       EVA     30        Curitiba
5           6    FELIPE     35        Brasília
6           7  GABRIELA     27         Goiânia
7           8      HUGO     45       São Paulo
8           9      IRIS     31          Recife
9          10      JOÃO     38        Curitiba

### Questão 3 - Transform

Filtre apenas clientes com idade maior que 30 anos.

In [12]:
maior_que_30 =clientes[clientes['idade']>=30]
maior_que_30

   cliente_id    nome  idade          cidade
1           2   BRUNO     35  Rio de Janeiro
3           4   DIEGO     41          Recife
4           5     EVA     30        Curitiba
5           6  FELIPE     35        Brasília
7           8    HUGO     45       São Paulo
8           9    IRIS     31          Recife
9          10    JOÃO     38        Curitiba

### Questão 4 - Transform

Filtre apenas vendas acima de R$ 1.000.

In [13]:
vendas

    venda_id  cliente_id   produto  valor        data
0        101           1  Notebook   3500  2025-01-10
1        102           2     Mouse     80  2025-01-11
2        103           1   Teclado    150  2025-01-12
3        104           3   Monitor   1200  2025-01-13
4        105           4  Notebook   3500  2025-01-14
5        106           5     Mouse     80  2025-01-15
6        107           6   Monitor   1200  2025-01-16
7        108           7   Teclado    150  2025-01-17
8        109           8  Notebook   3500  2025-01-18
9        110           9   Monitor   1200  2025-01-19
10       111          10     Mouse     80  2025-01-20
11       112           1   Monitor   1200  2025-01-21

In [14]:
maior_que_1000 = vendas[vendas['valor']>=1000]
maior_que_1000

    venda_id  cliente_id   produto  valor        data
0        101           1  Notebook   3500  2025-01-10
3        104           3   Monitor   1200  2025-01-13
4        105           4  Notebook   3500  2025-01-14
6        107           6   Monitor   1200  2025-01-16
8        109           8  Notebook   3500  2025-01-18
9        110           9   Monitor   1200  2025-01-19
11       112           1   Monitor   1200  2025-01-21

### Questão 5 - Transform

Crie uma nova coluna chamada:

In [18]:
import numpy as np

condicoes = [
    vendas['valor'] >= 3000,
    vendas['valor'] >= 1000
]

categorias = [
    'Premium',
    'Intermediaria'
]

vendas['categoria'] = np.select(
    condicoes,
    categorias,
    default='Basica'
)

In [19]:
vendas

    venda_id  cliente_id   produto  valor        data      categoria
0        101           1  Notebook   3500  2025-01-10        Premium
1        102           2     Mouse     80  2025-01-11         Basica
2        103           1   Teclado    150  2025-01-12         Basica
3        104           3   Monitor   1200  2025-01-13  Intermediaria
4        105           4  Notebook   3500  2025-01-14        Premium
5        106           5     Mouse     80  2025-01-15         Basica
6        107           6   Monitor   1200  2025-01-16  Intermediaria
7        108           7   Teclado    150  2025-01-17         Basica
8        109           8  Notebook   3500  2025-01-18        Premium
9        110           9   Monitor   1200  2025-01-19  Intermediaria
10       111          10     Mouse     80  2025-01-20         Basica
11       112           1   Monitor   1200  2025-01-21  Intermediaria

In [20]:
clientes, vendas

(   cliente_id      nome  idade          cidade
 0           1       ANA     22       São Paulo
 1           2     BRUNO     35  Rio de Janeiro
 2           3     CARLA     29       São Paulo
 3           4     DIEGO     41          Recife
 4           5       EVA     30        Curitiba
 5           6    FELIPE     35        Brasília
 6           7  GABRIELA     27         Goiânia
 7           8      HUGO     45       São Paulo
 8           9      IRIS     31          Recife
 9          10      JOÃO     38        Curitiba,
     venda_id  cliente_id   produto  valor        data      categoria
 0        101           1  Notebook   3500  2025-01-10        Premium
 1        102           2     Mouse     80  2025-01-11         Basica
 2        103           1   Teclado    150  2025-01-12         Basica
 3        104           3   Monitor   1200  2025-01-13  Intermediaria
 4        105           4  Notebook   3500  2025-01-14        Premium
 5        106           5     Mouse     80  2025-01-15         Basica
 6        107           6   Monitor   1200  2025-01-16  Intermediaria
 7        108           7   Teclado    150  2025-01-17         Basica
 8        109           8  Notebook   3500  2025-01-18        Premium
 9        110           9   Monitor   1200  2025-01-19  Intermediaria
 10       111          10     Mouse     80  2025-01-20         Basica
 11       112           1   Monitor   1200  2025-01-21  Intermediaria)

In [26]:
df = pd.merge(clientes, vendas, on='cliente_id')
df

,cliente_id,nome,idade,cidade,venda_id,produto,valor,data,categoria
0,1,ANA,22,São Paulo,101,Notebook,3500,2025-01-10,Premium
1,1,ANA,22,São Paulo,103,Teclado,150,2025-01-12,Basica
2,1,ANA,22,São Paulo,112,Monitor,1200,2025-01-21,Intermediaria
3,2,BRUNO,35,Rio de Janeiro,102,Mouse,80,2025-01-11,Basica
4,3,CARLA,29,São Paulo,104,Monitor,1200,2025-01-13,Intermediaria
5,4,DIEGO,41,Recife,105,Notebook,3500,2025-01-14,Premium
6,5,EVA,30,Curitiba,106,Mouse,80,2025-01-15,Basica
7,6,FELIPE,35,Brasília,107,Monitor,1200,2025-01-16,Intermediaria
8,7,GABRIELA,27,Goiânia,108,Teclado,150,2025-01-17,Basica
9,8,HUGO,45,São Paulo,109,Notebook,3500,2025-01-18,Premium
10,9,IRIS,31,Recife,110,Monitor,1200,2025-01-19,Intermediaria
11,10,JOÃO,38,Curitiba,111,Mouse,80,2025-01-20,Basica

### Questão 7 - Transform

Calcule o total gasto por cliente.

In [37]:
df.columns

Index(['cliente_id',       'nome',      'idade',     'cidade',   'venda_id',
          'produto',      'valor',       'data',  'categoria',        15840],
      dtype='object')

nome
ANA         4850
BRUNO         80
CARLA       1200
DIEGO       3500
EVA           80
FELIPE      1200
GABRIELA     150
HUGO        3500
IRIS        1200
JOÃO          80
Name: valor, dtype: int64