### Limpeza de dados

In [2]:
import pandas as pd

data = {'Id_producto':[1001,1002,1003,1003],
        'Cantidad_vendida':[30, None, 25,25],
        'Precio':[20.5,15.0,None, 22.5]}

df = pd.DataFrame(data)
df

   Id_producto  Cantidad_vendida  Precio
0         1001              30.0    20.5
1         1002               NaN    15.0
2         1003              25.0     NaN
3         1003              25.0    22.5

In [3]:
df.head()

   Id_producto  Cantidad_vendida  Precio
0         1001              30.0    20.5
1         1002               NaN    15.0
2         1003              25.0     NaN
3         1003              25.0    22.5