### Importa a biblioteca pandas, usada para trabalhar com tabelas de dados

In [39]:
import pandas as pd

#### Cria uma tabela com dados sujos para praticar limpeza

In [40]:
dados = {
    "nome": [" Ana ", "Bruno", "CARLA", "daniel", None, " Joaquim "],
    "idade": [25, None, 31, -5, 40, -10],
    "cidade": ["São Paulo", "rio de janeiro", "CURITIBA", None, "salvador", "ANAPOLIS"],
    "email": ["ana@email.com", "bruno@email.com", None, "daniel@email.com", "sem_email", None]
}

#### Transforma o dicionário em um DataFrame, que é uma tabela do pandas

In [41]:
df = pd.DataFrame(dados)

### Mostra a tabela original antes da limpeza

In [42]:
df

        nome  idade          cidade             email
0       Ana    25.0       São Paulo     ana@email.com
1      Bruno    NaN  rio de janeiro   bruno@email.com
2      CARLA   31.0        CURITIBA              None
3     daniel   -5.0            None  daniel@email.com
4       None   40.0        salvador         sem_email
5   Joaquim   -10.0        ANAPOLIS              None

### Remove espaços extras no começo e no fim dos nomes

In [43]:
df["status"] = ["ativo", None, "inativo", None, "ativo", None]

In [44]:
df['nome'] = df['nome'].str.strip()
df

      nome  idade          cidade             email   status
0      Ana   25.0       São Paulo     ana@email.com    ativo
1    Bruno    NaN  rio de janeiro   bruno@email.com     None
2    CARLA   31.0        CURITIBA              None  inativo
3   daniel   -5.0            None  daniel@email.com     None
4     None   40.0        salvador         sem_email    ativo
5  Joaquim  -10.0        ANAPOLIS              None     None

### Padroniza os nomes para começar com letra maiúscula

In [45]:
df['nome'] = df['nome'].str.title()
df

      nome  idade          cidade             email   status
0      Ana   25.0       São Paulo     ana@email.com    ativo
1    Bruno    NaN  rio de janeiro   bruno@email.com     None
2    Carla   31.0        CURITIBA              None  inativo
3   Daniel   -5.0            None  daniel@email.com     None
4     None   40.0        salvador         sem_email    ativo
5  Joaquim  -10.0        ANAPOLIS              None     None

### Preenche nomes vazios com o texto "Nome não informado"

In [46]:
df['nome'] = df['nome'].fillna("Nome não informado")
df

                 nome  idade          cidade             email   status
0                 Ana   25.0       São Paulo     ana@email.com    ativo
1               Bruno    NaN  rio de janeiro   bruno@email.com     None
2               Carla   31.0        CURITIBA              None  inativo
3              Daniel   -5.0            None  daniel@email.com     None
4  Nome não informado   40.0        salvador         sem_email    ativo
5             Joaquim  -10.0        ANAPOLIS              None     None

### Preenche cidades vazias com o texto "Cidade não informada"

In [47]:
df['cidade'] = df['cidade'].fillna("Cidade não informada")
df

                 nome  idade                cidade             email   status
0                 Ana   25.0             São Paulo     ana@email.com    ativo
1               Bruno    NaN        rio de janeiro   bruno@email.com     None
2               Carla   31.0              CURITIBA              None  inativo
3              Daniel   -5.0  Cidade não informada  daniel@email.com     None
4  Nome não informado   40.0              salvador         sem_email    ativo
5             Joaquim  -10.0              ANAPOLIS              None     None

### Calcula a média das idades válidas, ignorando valores vazios e negativos

In [48]:
media_idade = df[df["idade"] > 0]["idade"].mean()
media_idade

np.float64(32.0)

### Substitui idade vazia pela média calculada

In [49]:
df['idade'] = df['idade'].fillna(media_idade)
df

                 nome  idade                cidade             email   status
0                 Ana   25.0             São Paulo     ana@email.com    ativo
1               Bruno   32.0        rio de janeiro   bruno@email.com     None
2               Carla   31.0              CURITIBA              None  inativo
3              Daniel   -5.0  Cidade não informada  daniel@email.com     None
4  Nome não informado   40.0              salvador         sem_email    ativo
5             Joaquim  -10.0              ANAPOLIS              None     None

### Substitui idades negativas pela média calculada

In [50]:
df.loc[df['idade'] < 0, 'idade'] = media_idade

### Arredonda as idades para não ficarem com muitas casas decimais

In [51]:
df['idade'] = df['idade'].round(0).astype(int)
df

                 nome  idade                cidade             email   status
0                 Ana     25             São Paulo     ana@email.com    ativo
1               Bruno     32        rio de janeiro   bruno@email.com     None
2               Carla     31              CURITIBA              None  inativo
3              Daniel     32  Cidade não informada  daniel@email.com     None
4  Nome não informado     40              salvador         sem_email    ativo
5             Joaquim     32              ANAPOLIS              None     None

### Preenche emails vazios com "email_nao_informado"

In [52]:
df['email'] = df['email'].fillna("email_nao_encontrado")
df

,nome,idade,cidade,email,status
0,Ana,25,São Paulo,ana@email.com,ativo
1,Bruno,32,rio de janeiro,bruno@email.com,None
2,Carla,31,CURITIBA,email_nao_encontrado,inativo
3,Daniel,32,Cidade não informada,daniel@email.com,None
4,Nome não informado,40,salvador,sem_email,ativo
5,Joaquim,32,ANAPOLIS,email_nao_encontrado,None

### Cria uma coluna dizendo se o email parece válido

In [53]:
df['email_válido'] = df['email'].str.contains('@')
df

,nome,idade,cidade,email,status,email_válido
0,Ana,25,São Paulo,ana@email.com,ativo,True
1,Bruno,32,rio de janeiro,bruno@email.com,None,True
2,Carla,31,CURITIBA,email_nao_encontrado,inativo,False
3,Daniel,32,Cidade não informada,daniel@email.com,None,True
4,Nome não informado,40,salvador,sem_email,ativo,False
5,Joaquim,32,ANAPOLIS,email_nao_encontrado,None,False

### Mostra a tabela depois da limpeza

In [54]:
df

,nome,idade,cidade,email,status,email_válido
0,Ana,25,São Paulo,ana@email.com,ativo,True
1,Bruno,32,rio de janeiro,bruno@email.com,None,True
2,Carla,31,CURITIBA,email_nao_encontrado,inativo,False
3,Daniel,32,Cidade não informada,daniel@email.com,None,True
4,Nome não informado,40,salvador,sem_email,ativo,False
5,Joaquim,32,ANAPOLIS,email_nao_encontrado,None,False