### Importa a biblioteca pandas, usada para trabalhar com tabelas de dados

In [1]:
import pandas as pd

#### Cria uma tabela com dados sujos para praticar limpeza

In [2]:
dados = {
    "nome": [" Ana ", "Bruno", "CARLA", "daniel", None],
    "idade": [25, None, 31, -5, 40],
    "cidade": ["São Paulo", "rio de janeiro", "CURITIBA", None, "salvador"],
    "email": ["ana@email.com", "bruno@email.com", None, "daniel@email.com", "sem_email"]
}

#### Transforma o dicionário em um DataFrame, que é uma tabela do pandas

In [3]:
df = pd.DataFrame(dados)

### Mostra a tabela original antes da limpeza

In [4]:
df

     nome  idade          cidade             email
0    Ana    25.0       São Paulo     ana@email.com
1   Bruno    NaN  rio de janeiro   bruno@email.com
2   CARLA   31.0        CURITIBA              None
3  daniel   -5.0            None  daniel@email.com
4    None   40.0        salvador         sem_email

### Remove espaços extras no começo e no fim dos nomes

In [6]:
df['nome'] = df['nome'].str.strip()
df

     nome  idade          cidade             email
0     Ana   25.0       São Paulo     ana@email.com
1   Bruno    NaN  rio de janeiro   bruno@email.com
2   CARLA   31.0        CURITIBA              None
3  daniel   -5.0            None  daniel@email.com
4    None   40.0        salvador         sem_email

### Padroniza os nomes para começar com letra maiúscula

In [7]:
df['nome'] = df['nome'].str.title()
df

     nome  idade          cidade             email
0     Ana   25.0       São Paulo     ana@email.com
1   Bruno    NaN  rio de janeiro   bruno@email.com
2   Carla   31.0        CURITIBA              None
3  Daniel   -5.0            None  daniel@email.com
4    None   40.0        salvador         sem_email

### Preenche nomes vazios com o texto "Nome não informado"

In [9]:
df['nome'] = df['nome'].fillna("Nome não informado")
df

                 nome  idade          cidade             email
0                 Ana   25.0       São Paulo     ana@email.com
1               Bruno    NaN  rio de janeiro   bruno@email.com
2               Carla   31.0        CURITIBA              None
3              Daniel   -5.0            None  daniel@email.com
4  Nome não informado   40.0        salvador         sem_email

### Preenche cidades vazias com o texto "Cidade não informada"