### Importar pacotes

In [4]:
import pandas as pd

### Criar o dataset

In [5]:
df = pd.DataFrame({
    'cliente': ['A','B','B','C','D','D'],
    'valor': [10,20,20,30,40,40]
})

1. Identificar duplicados.

In [6]:
df[df.duplicated()]

  cliente  valor
2       B     20
5       D     40

2. Contar quantos existem.

In [7]:
df.duplicated().sum()

np.int64(2)

3. Remover duplicados.

In [8]:
df = df.drop_duplicates()

4. Mostrar dataframe final.

In [9]:
df

  cliente  valor
0       A     10
1       B     20
3       C     30
4       D     40