Primeiro, crie este DataFrame:

In [62]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'nome': ['Ana', 'Bruno', np.nan, 'Carlos', 'Ana'],
    'idade': [25, np.nan, 30, 150, 25],
    'salario': [3000, 4000, np.nan, 5000, 3000]
})

df

     nome  idade  salario
0     Ana   25.0   3000.0
1   Bruno    NaN   4000.0
2     NaN   30.0      NaN
3  Carlos  150.0   5000.0
4     Ana   25.0   3000.0

### Questão 1

Como descobrir quantos valores nulos existem em cada coluna?

In [65]:
df.isnull().sum()

nome       1
idade      1
salario    1
dtype: int64

### Questão 2

Como visualizar apenas as linhas que possuem valores nulos?

In [68]:
df[df.isnull().any(axis=1)]

    nome  idade  salario
1  Bruno    NaN   4000.0
2    NaN   30.0      NaN

### Questão 3

Como substituir os valores nulos da coluna idade pela média das idades?

0     25.0
1     57.5
2     30.0
3    150.0
4     25.0
Name: idade, dtype: float64

### Questão 4

Como substituir os valores nulos da coluna salario pela média?

0    3000.0
1    4000.0
2    3750.0
3    5000.0
4    3000.0
Name: salario, dtype: float64

### Questão 5

Como descobrir se existem linhas duplicadas?

0    False
1    False
2    False
3    False
4     True
dtype: bool

### Questão 6

Como visualizar as linhas duplicadas?

  nome  idade  salario
4  Ana   25.0   3000.0

### Questão 7

Como remover as duplicatas?

     nome  idade  salario
0     Ana   25.0   3000.0
1   Bruno   57.5   4000.0
2     NaN   30.0   3750.0
3  Carlos  150.0   5000.0

### Questão 8

Como localizar idades maiores que 100 anos?

     nome  idade  salario
3  Carlos  150.0   5000.0

### Questão 9

Como substituir a idade 150 pela mediana das idades?

     nome  idade  salario
0     Ana  25.00   3000.0
1   Bruno  57.50   4000.0
2     NaN  30.00   3750.0
3  Carlos  43.75   5000.0

### Questão 10

Como verificar se ainda existem valores nulos?

nome       1
idade      0
salario    0
dtype: int64

### Questão 11

Como substituir o nome nulo por "Desconhecido"?

0             Ana
1           Bruno
2    Desconhecido
3          Carlos
Name: nome, dtype: object

### Questão 12

Como verificar se o DataFrame está limpo?

Nulos:
nome       0
idade      0
salario    0
dtype: int64

Duplicados:
0

### Desafio Final

Crie uma função que mostre um relatório de qualidade dos dados:

Quantidade de linhas: 4
Quantidade de colunas: 3

Valores nulos:
nome       0
idade      0
salario    0
dtype: int64

Duplicados:
0