Primeiro, crie este DataFrame:

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'nome': ['Ana', 'Bruno', np.nan, 'Carlos', 'Ana'],
    'idade': [25, np.nan, 30, 150, 25],
    'salario': [3000, 4000, np.nan, 5000, 3000]
})

df

     nome  idade  salario
0     Ana   25.0   3000.0
1   Bruno    NaN   4000.0
2     NaN   30.0      NaN
3  Carlos  150.0   5000.0
4     Ana   25.0   3000.0

### Questão 1

Como descobrir quantos valores nulos existem em cada coluna?

In [3]:
df.isnull().sum()

nome       1
idade      1
salario    1
dtype: int64

### Questão 2

Como visualizar apenas as linhas que possuem valores nulos?

In [6]:
df[df.isnull().any(axis=1)]

    nome  idade  salario
1  Bruno    NaN   4000.0
2    NaN   30.0      NaN

### Questão 3

Como substituir os valores nulos da coluna idade pela média das idades?

In [7]:
age_medium = df.idade.mean()
age_medium

np.float64(57.5)

In [8]:
df.idade = df.idade.fillna(age_medium)
df.idade

0     25.0
1     57.5
2     30.0
3    150.0
4     25.0
Name: idade, dtype: float64

### Questão 4

Como substituir os valores nulos da coluna salario pela média?