In [8]:
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
dados = {
    'cliente':['Joao', 'Maria', 'Pedro', 'Ana', 'Carlos', 'Lucas', 'Marcos', 'Julia', 'Paulo', 'Fernanda'], 
    'produto':['Notebook', 'Mouse', 'Teclado', 'Notebook', 'Monitor', 'Mouse', 'Notebook', 'Headset', 'Monitor', 'Teclado'],
    'cidade':['Anápolis', 'Goiânia', 'Anápolis', 'Brasília', 'Goiânia', 'Anápolis', 'Brasília', 'Goiânia', 'Anápolis', 'Brasília'],
    'quantidade':[2,10,5,1,3,8,2,6,2,4],
    'preco':[3500,80,150,3500,1200,80,53500,300,1200,150]

}

In [10]:
df_vendas = pd.DataFrame(dados)

In [11]:
df_vendas['total'] = (df_vendas['quantidade']*df_vendas['preco'])
df_vendas

    cliente   produto    cidade  quantidade  preco   total
0      Joao  Notebook  Anápolis           2   3500    7000
1     Maria     Mouse   Goiânia          10     80     800
2     Pedro   Teclado  Anápolis           5    150     750
3       Ana  Notebook  Brasília           1   3500    3500
4    Carlos   Monitor   Goiânia           3   1200    3600
5     Lucas     Mouse  Anápolis           8     80     640
6    Marcos  Notebook  Brasília           2  53500  107000
7     Julia   Headset   Goiânia           6    300    1800
8     Paulo   Monitor  Anápolis           2   1200    2400
9  Fernanda   Teclado  Brasília           4    150     600

In [12]:
faturamento_produto = (
    df_vendas.groupby('produto')['total'].sum()
)
df_vendas

    cliente   produto    cidade  quantidade  preco   total
0      Joao  Notebook  Anápolis           2   3500    7000
1     Maria     Mouse   Goiânia          10     80     800
2     Pedro   Teclado  Anápolis           5    150     750
3       Ana  Notebook  Brasília           1   3500    3500
4    Carlos   Monitor   Goiânia           3   1200    3600
5     Lucas     Mouse  Anápolis           8     80     640
6    Marcos  Notebook  Brasília           2  53500  107000
7     Julia   Headset   Goiânia           6    300    1800
8     Paulo   Monitor  Anápolis           2   1200    2400
9  Fernanda   Teclado  Brasília           4    150     600