### Exemplo 1: criando e visualizando dados

In [3]:
import pandas as pd

In [4]:
dados = {'produto':['Mouse', 'Teclado', 'Caderno', 'Caneta', 'Monitor'],
         'categoria':['Informática', 'Informática', 'Papelaria', 'Papelaria', 'Informática'],
         'preco':[50,120,25,5,900],
         'quantidade':[2,1,4,10,1]}

In [5]:
df = pd.DataFrame(dados)

In [6]:
df

   produto    categoria  preco  quantidade
0    Mouse  Informática     50           2
1  Teclado  Informática    120           1
2  Caderno    Papelaria     25           4
3   Caneta    Papelaria      5          10
4  Monitor  Informática    900           1

In [7]:
df.head()

   produto    categoria  preco  quantidade
0    Mouse  Informática     50           2
1  Teclado  Informática    120           1
2  Caderno    Papelaria     25           4
3   Caneta    Papelaria      5          10
4  Monitor  Informática    900           1

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   produto     5 non-null      object
 1   categoria   5 non-null      object
 2   preco       5 non-null      int64
 3   quantidade  5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

### Exemplo 2: filtrando e resumindo

In [1]:
dados = {
    'produto':['Mouse', 'Teclado', 'Caderno', 'Caneta', 'Monitor'],
    'categoria':['Informática','Informática', 'Papelaria', 'Papelaria', 'Informática'],
    'preco':[50,120,25,5,900],
    'quantidade':[2,1,4,10,1]
}

In [3]:
import pandas as pd

df = pd.DataFrame(dados)

In [4]:
df.head()

   produto    categoria  preco  quantidade
0    Mouse  Informática     50           2
1  Teclado  Informática    120           1
2  Caderno    Papelaria     25           4
3   Caneta    Papelaria      5          10
4  Monitor  Informática    900           1

### Criando uma nova coluna

### Filtrando, parecido com WHERE em SQL

### Estatísticas simples

### Agrupamento, parecido com GROUP BY em SQL