### 1. Análise de clientes

In [5]:
import pandas as pd

dados = {
    "nome": ["Ana", "Bruno", "Carla", "Diego", "Eva"],
    "idade": [22, 35, 29, 41, 30],
    "cidade": ["São Paulo", "Rio de Janeiro", "São Paulo", "Recife", "Curitiba"],
    "compras": [3, 8, 5, 2, 10],
}

df = pd.DataFrame(dados)

2. Filtre clientes de ``São Paulo``.

In [6]:
clientes_de_SP = df[df['cidade'] == 'São Paulo']
clientes_de_SP

    nome  idade     cidade  compras
0    Ana     22  São Paulo        3
2  Carla     29  São Paulo        5

3. Filtre clientes com mais de ``5`` compras.

In [7]:
clientes_5_ou_mais_compras = df[df['compras']>=5]
clientes_5_ou_mais_compras

    nome  idade          cidade  compras
1  Bruno     35  Rio de Janeiro        8
2  Carla     29       São Paulo        5
4    Eva     30        Curitiba       10

4. Calcule a média de idade.

In [8]:
media_idade = df['idade'].mean()
media_idade

np.float64(31.4)

### 2. Ordenação e novas colunas

1. Ordene os clientes por ``compras``, do maior para o menor.

In [9]:
df_ordenado_compras = df.sort_values(by='compras', ascending=False)
df_ordenado_compras

    nome  idade          cidade  compras
4    Eva     30        Curitiba       10
1  Bruno     35  Rio de Janeiro        8
2  Carla     29       São Paulo        5
0    Ana     22       São Paulo        3
3  Diego     41          Recife        2

2. Crie uma coluna chamada ``cliente_frequente``.

In [16]:
import numpy as np
df['cliente_frequente'] = np.where(
    df['compras']>5,
    'Frequente',
    'Não frequente'
)

df

    nome  idade          cidade  compras cliente_frequente
0    Ana     22       São Paulo        3     Não frequente
1  Bruno     35  Rio de Janeiro        8         Frequente
2  Carla     29       São Paulo        5     Não frequente
3  Diego     41          Recife        2     Não frequente
4    Eva     30        Curitiba       10         Frequente