### Limpeza de Dados e EDA Profissional

Uma regra muito conhecida em Data Analytics é:

- 80% do tempo = preparando dados
- 20% do tempo = analisando dados

In [1]:
import pandas as pd

In [5]:

dados = {
    "nome": ["Ana", "Pedro", "Julia", "Pedro", None],
    "idade": [25, 30, None, 30, 40],
    "salario": [3000, 5000, 4000, 5000, None]
}

df = pd.DataFrame(dados)
df

    nome  idade  salario
0    Ana   25.0   3000.0
1  Pedro   30.0   5000.0
2  Julia    NaN   4000.0
3  Pedro   30.0   5000.0
4   None   40.0      NaN

In [6]:
df.head()

    nome  idade  salario
0    Ana   25.0   3000.0
1  Pedro   30.0   5000.0
2  Julia    NaN   4000.0
3  Pedro   30.0   5000.0
4   None   40.0      NaN