### Limpeza de Dados e EDA Profissional

Uma regra muito conhecida em Data Analytics é:

- 80% do tempo = preparando dados
- 20% do tempo = analisando dados

In [1]:
import pandas as pd

In [5]:

dados = {
    "nome": ["Ana", "Pedro", "Julia", "Pedro", None],
    "idade": [25, 30, None, 30, 40],
    "salario": [3000, 5000, 4000, 5000, None]
}

df = pd.DataFrame(dados)
df

    nome  idade  salario
0    Ana   25.0   3000.0
1  Pedro   30.0   5000.0
2  Julia    NaN   4000.0
3  Pedro   30.0   5000.0
4   None   40.0      NaN

In [6]:
df.head()

    nome  idade  salario
0    Ana   25.0   3000.0
1  Pedro   30.0   5000.0
2  Julia    NaN   4000.0
3  Pedro   30.0   5000.0
4   None   40.0      NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nome     4 non-null      object
 1   idade    4 non-null      float64
 2   salario  4 non-null      float64
dtypes: float64(2), object(1)
memory usage: 252.0+ bytes

In [8]:
df.describe()

           idade      salario
count   4.000000     4.000000
mean   31.250000  4250.000000
std     6.291529   957.427108
min    25.000000  3000.000000
25%    28.750000  3750.000000
50%    30.000000  4500.000000
75%    32.500000  5000.000000
max    40.000000  5000.000000

### Passo 2 — Encontrar Valores Nulos

In [9]:
df.isnull().sum()

nome       1
idade      1
salario    1
dtype: int64

Tratando Valores Nulos

Opção 1 — Remover

In [11]:
df = df.dropna()
df

    nome  idade  salario
0    Ana   25.0   3000.0
1  Pedro   30.0   5000.0
3  Pedro   30.0   5000.0

### Opção 2 — Preencher

Idade média:

In [13]:
df['idade'] = df['idade'].fillna(
    df['idade'].mean()
)

df

    nome  idade  salario
0    Ana   25.0   3000.0
1  Pedro   30.0   5000.0
3  Pedro   30.0   5000.0

In [14]:
df['salario'] = df['salario'].fillna(
    df['salario'].mean()
)

### Passo 3 — Encontrar Duplicatas

Verificar:

In [15]:
df.duplicated()

0    False
1    False
3     True
dtype: bool

In [16]:
df.duplicated().sum()

np.int64(1)

In [17]:
df = df.drop_duplicates()

### Passo 4 — Tipos de Dados

Verificar:

In [18]:
df.dtypes

nome        object
idade      float64
salario    float64
dtype: object

In [19]:
df['idade'] = df['idade'].astype(int)

C:\Users\Olive\AppData\Local\Temp\ipykernel_11852\2362419120.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['idade'] = df['idade'].astype(int)

### Passo 5 — Estatísticas Importantes

Média:

In [20]:
df['salario'].mean()

np.float64(4000.0)

mediana

In [21]:
df['salario'].median()

4000.0

Desvio padrão:

In [22]:
df['salario'].std()

1414.213562373095

Máximo:

In [23]:
df['salario'].max()

5000.0

Mínimo

In [24]:
df['salario'].min()

3000.0

### Passo 6 — Filtragem Profissional

Salários acima da média:

In [25]:
df[df['salario']>df['salario'].mean()]

    nome  idade  salario
1  Pedro     30   5000.0

Funcionários acima de 30 anos:

In [27]:
df[df['idade']>30]

Empty DataFrame
Columns: [nome, idade, salario]
Index: []

In [28]:
df[
    (df['idade']>25) &
    (df['salario']>4000)
]

    nome  idade  salario
1  Pedro     30   5000.0

### Passo 7 — Criar Novas Colunas

Salário anual:

In [29]:
df['salario_anual'] = df['salario'] * 12

C:\Users\Olive\AppData\Local\Temp\ipykernel_11852\2019096231.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['salario_anual'] = df['salario'] * 12

Faixa salarial:

In [31]:
df["categoria"] = df["salario"].apply(
    lambda x: "Alta" if x > 5000 else "Normal"
)

C:\Users\Olive\AppData\Local\Temp\ipykernel_11852\866334860.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["categoria"] = df["salario"].apply(

### Agrupamentos

Tabela:

In [32]:
dados = {
    "departamento": ["TI","TI","RH","RH"],
    "salario": [5000,7000,4000,6000]
}

df = pd.DataFrame(dados)

Média por departamento:

In [33]:
df.groupby('departamento')['salario'].mean()

departamento
RH    5000.0
TI    6000.0
Name: salario, dtype: float64

Total por departamento:

In [34]:
df.groupby('departamento')['salario'].sum()

departamento
RH    10000
TI    12000
Name: salario, dtype: int64

### Exercício 1

Crie:

In [ ]:
dados = {
    "produto": ["Mouse","Mouse","Teclado","Monitor"],
    "vendas": [100,150,200,500]
}

In [37]:
df = pd.DataFrame(dados)
df

   produto  vendas
0    Mouse     100
1    Mouse     150
2  Teclado     200
3  Monitor     500

1. Soma das vendas:

In [38]:
df['vendas'].sum()

np.int64(950)

2. Média:

In [39]:
df['vendas'].mean()

np.float64(237.5)

3. Maior valor:

In [40]:
df['vendas'].max()

500

4. Menor valor:

In [41]:
df['vendas'].min()

100

Agrupe por produto:

In [42]:
df.groupby('produto')

soma

In [43]:
df.groupby('produto').sum()

         vendas
produto
Monitor     500
Mouse       250
Teclado     200

média

In [44]:
df.groupby('produto').mean()

         vendas
produto
Monitor   500.0
Mouse     125.0
Teclado   200.0

quantidade

In [45]:
df.groupby('produto').count()

         vendas
produto
Monitor       1
Mouse         2
Teclado       1

### Mini Projeto

Você é analista de RH.

In [46]:
dados = {
    "nome": ["Ana","Pedro","Julia","Carlos"],
    "departamento": ["TI","TI","RH","Financeiro"],
    "salario": [5000,7000,4000,8000]
}

In [48]:
df = pd.DataFrame(dados)
df

     nome departamento  salario
0     Ana           TI     5000
1   Pedro           TI     7000
2   Julia           RH     4000
3  Carlos   Financeiro     8000

### Responda:

1. Salário médio da empresa.

In [49]:
df['salario'].mean()

np.float64(6000.0)

2. Maior salário.

In [50]:
df['salario'].max()

8000

3. Menor salário.

4. Média por departamento.

5. Funcionários acima da média.