### Problema 2 — Dados Duplicados

In [90]:
import pandas as pd

In [91]:
df = pd.DataFrame({
    'cliente':['A', 'B', 'B' ,'C', 'D', 'D'],
    'valor':[10,20,20,30,40,40]
})

1. Identificar registros duplicados

Crie uma coluna temporária ou mostre quais linhas são duplicadas.

In [92]:
df['duplicados'] = df.duplicated()
df

  cliente  valor  duplicados
0       A     10       False
1       B     20       False
2       B     20        True
3       C     30       False
4       D     40       False
5       D     40        True

In [93]:
df = df.drop('duplicados', axis=1)

In [94]:
df

  cliente  valor
0       A     10
1       B     20
2       B     20
3       C     30
4       D     40
5       D     40

2. Contar quantos duplicados existem

Retorne apenas a quantidade.

3. Remover os registros duplicados

Crie um novo DataFrame sem duplicados.

4. Mostrar o DataFrame final