### Problema 2 — Dados Duplicados

In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame({
    'cliente':['A', 'B', 'B' ,'C', 'D', 'D'],
    'valor':[10,20,20,30,40,40]
})

1. Identificar registros duplicados

Crie uma coluna temporária ou mostre quais linhas são duplicadas.

In [9]:
df[df.duplicated()]

  cliente  valor
2       B     20
5       D     40

2. Contar quantos duplicados existem

Retorne apenas a quantidade.

In [10]:
df.duplicated().sum()

np.int64(2)

3. Remover os registros duplicados

Crie um novo DataFrame sem duplicados.

In [11]:
df = df.drop_duplicates()

4. Mostrar o DataFrame final

In [12]:
df

  cliente  valor
0       A     10
1       B     20
3       C     30
4       D     40