### Problema 2 — Dados Duplicados

In [31]:
import pandas as pd

In [32]:
df = pd.DataFrame({
    'cliente':['A', 'B', 'B' ,'C', 'D', 'D'],
    'valor':[10,20,20,30,40,40]
})

1. Identificar registros duplicados

Crie uma coluna temporária ou mostre quais linhas são duplicadas.

In [34]:
df['duplicated'] = df.duplicated()
df

  cliente  valor  duplicated
0       A     10       False
1       B     20       False
2       B     20       False
3       C     30       False
4       D     40       False
5       D     40       False

In [35]:
df = df.drop('duplicated', axis=1)
df

  cliente  valor
0       A     10
1       B     20
2       B     20
3       C     30
4       D     40
5       D     40

2. Contar quantos duplicados existem

Retorne apenas a quantidade.

In [36]:
df.duplicated().sum()

np.int64(2)

3. Remover os registros duplicados

Crie um novo DataFrame sem duplicados.

In [39]:
df.drop_duplicates(inplace=True)
df

  cliente  valor
0       A     10
1       B     20
3       C     30
4       D     40

4. Mostrar o DataFrame final

In [40]:
df

  cliente  valor
0       A     10
1       B     20
3       C     30
4       D     40