### Problema 2 — Dados Duplicados

In [27]:
import pandas as pd

In [28]:
df = pd.DataFrame({
    'cliente':['A', 'B', 'B' ,'C', 'D', 'D'],
    'valor':[10,20,20,30,40,40]
})

1. Identificar registros duplicados

Crie uma coluna temporária ou mostre quais linhas são duplicadas.

In [29]:
df['linhas_duplicadas'] = df.duplicated()
df

  cliente  valor  linhas_duplicadas
0       A     10              False
1       B     20              False
2       B     20               True
3       C     30              False
4       D     40              False
5       D     40               True

2. Contar quantos duplicados existem

Retorne apenas a quantidade.

In [30]:
df.duplicated(subset=['cliente']).sum()

np.int64(2)

3. Remover os registros duplicados

Crie um novo DataFrame sem duplicados.

In [37]:
df = df.drop(columns=['linhas_duplicadas'])

In [38]:
df

  cliente  valor
0       A     10
1       B     20
2       B     20
3       C     30
4       D     40
5       D     40

In [41]:
df = df.drop_duplicates()

4. Mostrar o DataFrame final

In [42]:
df

  cliente  valor
0       A     10
1       B     20
3       C     30
4       D     40