In [10]:
import pandas as pd

dados = {
    "nome": ["João", "Maria", "Pedro", "João", "Ana", "Carlos"],
    "idade": [32, 28, None, 32, 29, 40]
}

df = pd.DataFrame(dados)

print("Antes:")
print(df)

media_idade = df["idade"].mean()

df["idade"] = df["idade"].fillna(media_idade)

print("\nDepois:")
print(df)

Antes:
     nome  idade
0    João   32.0
1   Maria   28.0
2   Pedro    NaN
3    João   32.0
4     Ana   29.0
5  Carlos   40.0

Depois:
     nome  idade
0    João   32.0
1   Maria   28.0
2   Pedro   32.2
3    João   32.0
4     Ana   29.0
5  Carlos   40.0

In [11]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
dtype: bool

In [12]:
df.duplicated().sum()

np.int64(1)

In [13]:
df.drop_duplicates()

     nome  idade
0    João   32.0
1   Maria   28.0
2   Pedro   32.2
4     Ana   29.0
5  Carlos   40.0

In [15]:
df = df.drop_duplicates()
df

     nome  idade
0    João   32.0
1   Maria   28.0
2   Pedro   32.2
4     Ana   29.0
5  Carlos   40.0