In [2]:
import pandas as pd

dados = {
    "nome": [
        "João",
        "Maria",
        "Pedro",
        "João",
        "Ana"
    ],
    
    "idade": [
        32,
        28,
        None,
        32,
        29
    ],
    
    "salario": [
        3500,
        4200,
        3800,
        3500,
        None
    ]
}

df = pd.DataFrame(dados)

print("DADOS ORIGINAIS")
print(df)

print("\nVALORES AUSENTES")
print(df.isnull().sum())

print("\nDUPLICADOS")
print(df.duplicated().sum())

DADOS ORIGINAIS
    nome  idade  salario
0   João   32.0   3500.0
1  Maria   28.0   4200.0
2  Pedro    NaN   3800.0
3   João   32.0   3500.0
4    Ana   29.0      NaN

VALORES AUSENTES
nome       0
idade      1
salario    1
dtype: int64

DUPLICADOS
1

# Remover duplicates

In [4]:
df = df.drop_duplicates()
df

    nome  idade  salario
0   João   32.0   3500.0
1  Maria   28.0   4200.0
2  Pedro    NaN   3800.0
4    Ana   29.0      NaN

In [5]:
media_idade = df['idade'].mean()
media_idade

np.float64(29.666666666666668)

In [6]:
df['idade'] = df['idade'].fillna(media_idade)
df

    nome      idade  salario
0   João  32.000000   3500.0
1  Maria  28.000000   4200.0
2  Pedro  29.666667   3800.0
4    Ana  29.000000      NaN

# Preencher salário com a média

In [7]:
media_salario = df['salario'].mean()
media_salario

np.float64(3833.3333333333335)

In [8]:
df['salario'] = df['salario'].fillna(media_salario)
df

    nome      idade      salario
0   João  32.000000  3500.000000
1  Maria  28.000000  4200.000000
2  Pedro  29.666667  3800.000000
4    Ana  29.000000  3833.333333