In [50]:
import pandas as pd

In [51]:
dados = {
    'nome':['joão', 'MARIA', 'João', 'pedro', 'ANA'],
    'idade':[30,None, 30,200,25],
    'cidade':['goiania', 'Goiânia', 'GOIANIA', 'Brasília', ' brasilia '],
    'salario':[3500,4200,3500,-500,None]
}

In [52]:
df = pd.DataFrame(dados)
df

    nome  idade      cidade  salario
0   joão   30.0     goiania   3500.0
1  MARIA    NaN     Goiânia   4200.0
2   João   30.0     GOIANIA   3500.0
3  pedro  200.0    Brasília   -500.0
4    ANA   25.0   brasilia       NaN

In [53]:
df['nome'] = (df['nome'].str.lower().str.strip().str.capitalize())
df

    nome  idade      cidade  salario
0   João   30.0     goiania   3500.0
1  Maria    NaN     Goiânia   4200.0
2   João   30.0     GOIANIA   3500.0
3  Pedro  200.0    Brasília   -500.0
4    Ana   25.0   brasilia       NaN

In [54]:
df['cidade'] = (df['cidade'].str.lower().str.strip().str.capitalize())
df.loc[0,'cidade'] = "Goiânia"
df.loc[2,'cidade'] = "Goiânia"
df

    nome  idade    cidade  salario
0   João   30.0   Goiânia   3500.0
1  Maria    NaN   Goiânia   4200.0
2   João   30.0   Goiânia   3500.0
3  Pedro  200.0  Brasília   -500.0
4    Ana   25.0  Brasilia      NaN

In [55]:
df.loc[df['idade']>120, 'idade'] = None
df

    nome  idade    cidade  salario
0   João   30.0   Goiânia   3500.0
1  Maria    NaN   Goiânia   4200.0
2   João   30.0   Goiânia   3500.0
3  Pedro    NaN  Brasília   -500.0
4    Ana   25.0  Brasilia      NaN

In [56]:
df.loc[df['salario'] < 0, 'salario'] = None
df

    nome  idade    cidade  salario
0   João   30.0   Goiânia   3500.0
1  Maria    NaN   Goiânia   4200.0
2   João   30.0   Goiânia   3500.0
3  Pedro    NaN  Brasília      NaN
4    Ana   25.0  Brasilia      NaN

In [57]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [58]:
df = df.drop_duplicates()
df

    nome  idade    cidade  salario
0   João   30.0   Goiânia   3500.0
1  Maria    NaN   Goiânia   4200.0
3  Pedro    NaN  Brasília      NaN
4    Ana   25.0  Brasilia      NaN

In [59]:
df.to_csv('dados_de_clientes_limpo.csv', index=False)