In [1]:
import pandas as pd

In [2]:
dados = {
    "nome":['Ana', 'João', 'Maria', 'Pedro', 'Carlos'],
    'idade':[25,40,32,28,50],
    'salario':[3500,5000,4500,2800,7000]
}

In [3]:
df = pd.DataFrame(dados)
df

     nome  idade  salario
0     Ana     25     3500
1    João     40     5000
2   Maria     32     4500
3   Pedro     28     2800
4  Carlos     50     7000

In [4]:
df.head()

     nome  idade  salario
0     Ana     25     3500
1    João     40     5000
2   Maria     32     4500
3   Pedro     28     2800
4  Carlos     50     7000

In [6]:
df.shape

(5, 3)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nome     5 non-null      object
 1   idade    5 non-null      int64
 2   salario  5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [8]:
df.describe()

           idade      salario
count   5.000000     5.000000
mean   35.000000  4560.000000
std    10.099505  1610.279479
min    25.000000  2800.000000
25%    28.000000  3500.000000
50%    32.000000  4500.000000
75%    40.000000  5000.000000
max    50.000000  7000.000000

In [9]:
df.nome

0       Ana
1      João
2     Maria
3     Pedro
4    Carlos
Name: nome, dtype: object

In [10]:
df.idade

0    25
1    40
2    32
3    28
4    50
Name: idade, dtype: int64

In [13]:
df[['nome', 'salario']]

     nome  salario
0     Ana     3500
1    João     5000
2   Maria     4500
3   Pedro     2800
4  Carlos     7000

In [14]:
df[df['salario']>4000]

     nome  idade  salario
1    João     40     5000
2   Maria     32     4500
4  Carlos     50     7000

In [15]:
df[df['idade']>=30]

     nome  idade  salario
1    João     40     5000
2   Maria     32     4500
4  Carlos     50     7000

# Duas condições

In [16]:
df[
    (df['idade'] >= 30) &
    (df['salario'] > 4000)
]

     nome  idade  salario
1    João     40     5000
2   Maria     32     4500
4  Carlos     50     7000

In [17]:
df[
    (df['salario'] > 6000) |
    (df['idade'] < 30)
]

     nome  idade  salario
0     Ana     25     3500
3   Pedro     28     2800
4  Carlos     50     7000