In [1]:
import pandas as pd

In [2]:
dados = {
    "nome":['Ana', 'João', 'Maria', 'Pedro', 'Carlos'],
    'idade':[25,40,32,28,50],
    'salario':[3500,5000,4500,2800,7000]
}

In [3]:
df = pd.DataFrame(dados)
df

     nome  idade  salario
0     Ana     25     3500
1    João     40     5000
2   Maria     32     4500
3   Pedro     28     2800
4  Carlos     50     7000

In [4]:
df.head()

     nome  idade  salario
0     Ana     25     3500
1    João     40     5000
2   Maria     32     4500
3   Pedro     28     2800
4  Carlos     50     7000

In [6]:
df.shape

(5, 3)