In [1]:
import pandas as pd

In [2]:
dados = {
    "nome":["Ana", "João", "Maria", "Pedro", "Carlos"],
    "idade":[25,40,32,28,50],
    "salario":[3500,5000,4500,2800,7000]
}

In [3]:
df = pd.DataFrame(dados)
df

     nome  idade  salario
0     Ana     25     3500
1    João     40     5000
2   Maria     32     4500
3   Pedro     28     2800
4  Carlos     50     7000

In [5]:
clientes_altos_salarios = df[df["salario"] > 4000]
clientes_altos_salarios

     nome  idade  salario
1    João     40     5000
2   Maria     32     4500
4  Carlos     50     7000

In [7]:
df.sort_values("salario")

     nome  idade  salario
3   Pedro     28     2800
0     Ana     25     3500
2   Maria     32     4500
1    João     40     5000
4  Carlos     50     7000

In [8]:
df.sort_values("salario", ascending=False)

     nome  idade  salario
4  Carlos     50     7000
1    João     40     5000
2   Maria     32     4500
0     Ana     25     3500
3   Pedro     28     2800

# Ordenado opr duas colunas

In [9]:
df.sort_values(["idade", "salario"],
               ascending=[True, False])

     nome  idade  salario
0     Ana     25     3500
3   Pedro     28     2800
2   Maria     32     4500
1    João     40     5000
4  Carlos     50     7000

In [10]:
df['salario'].mean()

np.float64(4560.0)

In [11]:
df['idade'].mean()

np.float64(35.0)