In [1]:
import pandas as pd

In [2]:
dados = {
    'nome':['Ana', 'João', 'Maria', 'Pedro'],
    'salario':[3500,5000,4500,2800]
}

df = pd.DataFrame(dados)
df

    nome  salario
0    Ana     3500
1   João     5000
2  Maria     4500
3  Pedro     2800

In [3]:
df['salario_anual'] = df['salario']*12

In [4]:
df['bonus'] = df['salario']*0.3
df

    nome  salario  salario_anual   bonus
0    Ana     3500          42000  1050.0
1   João     5000          60000  1500.0
2  Maria     4500          54000  1350.0
3  Pedro     2800          33600   840.0

In [5]:
df.loc[
    df['salario'] > 4000,
    ['nome', 'salario']
]

    nome  salario
1   João     5000
2  Maria     4500

In [6]:
df.iloc[0]

nome                Ana
salario            3500
salario_anual     42000
bonus            1050.0
Name: 0, dtype: object

In [7]:
df.iloc[0:3]

    nome  salario  salario_anual   bonus
0    Ana     3500          42000  1050.0
1   João     5000          60000  1500.0
2  Maria     4500          54000  1350.0

In [8]:
df.iloc[0:3, 0:2]

    nome  salario
0    Ana     3500
1   João     5000
2  Maria     4500